"""Write the manuscript graph as a plain Cypher script (run with cypher-shell or paste small parts).

    python3 -m heritage_rag.export_cypher <csv-dir> <out.cypher> [--batch 500]

The script is idempotent (MERGE) and builds the same graph as `load_neo4j`: nodes carry `:Entity` plus their
CIDOC class as a label, every relationship keeps its citation, and all columns are stored as properties.
Run:  cypher-shell -a bolt://localhost:7687 -u neo4j -p <password> -f out.cypher
"""
import argparse
from collections import defaultdict

from .load_neo4j import read_graph
from .schema import CLASS_BY_TYPE, NODE_COLUMNS, EDGE_COLUMNS, RELATIONSHIPS
from .store import search_names

HEADER = """// Manuscript graph for Neo4j 5 (Cypher). Generated by heritage_rag.export_cypher.
// Source: Beta masahaft Manuscripts, Institutions, Persons and Works (Hiob-Ludolf-Zentrum fuer
// Aethiopistik, Hamburg), licensed CC BY-SA 4.0. The source records are drafts.
// This script is derived from them: keep the attribution and share it under the same licence.
// Nodes: {nodes}   Relationships: {edges}
"""


def cy_str(value):
    """Cypher single-quoted string literal."""
    s = str(value).replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return "'" + s + "'"


def cy_value(value):
    return repr(float(value)) if isinstance(value, float) else cy_str(value)


def cy_row(row, columns):
    """One row as a Cypher list, in column order. Lists of literals load far faster than maps of literals."""
    return "[" + ", ".join(cy_value(row.get(c, "")) for c in columns) + "]"


NODE_COLS = NODE_COLUMNS + ["search_names"]


def _assign(var, column, index):
    """`var.column = r[index]`; confidence is written back as a number."""
    value = f"toFloat(r[{index}])" if column == "confidence" else f"r[{index}]"
    return f"{var}.{column} = {value}"


def statements(nodes, edges, batch=500):
    """Yield Cypher statements. Rows are positional lists (r[0], r[1], ...) because Neo4j treats a large list of
    literal lists as one constant, but parses a large list of literal maps value by value (about 20x slower)."""
    allowed_classes = set(CLASS_BY_TYPE.values())
    yield "CREATE CONSTRAINT node_id IF NOT EXISTS FOR (n:Entity) REQUIRE n.id IS UNIQUE;"
    yield "CREATE INDEX entity_access IF NOT EXISTS FOR (n:Entity) ON (n.access_level);"
    node_set = ", ".join(_assign("n", c, i) for i, c in enumerate(NODE_COLS) if c != "id")
    by_class = defaultdict(list)
    for n in nodes.values():
        n = dict(n, search_names=search_names(n))
        by_class[n["cidoc_class"]].append(n)
    for cls in sorted(by_class):
        if cls not in allowed_classes:
            raise ValueError(f"unknown CIDOC class {cls}")
        rows = by_class[cls]
        for i in range(0, len(rows), batch):
            lst = ",\n  ".join(cy_row(r, NODE_COLS) for r in rows[i:i + batch])
            yield f"UNWIND [\n  {lst}\n] AS r\nMERGE (n:Entity {{id: r[0]}}) SET {node_set} SET n:`{cls}`;"
    edge_set = ", ".join(_assign("x", c, i) for i, c in enumerate(EDGE_COLUMNS))
    di, li = EDGE_COLUMNS.index("source_document"), EDGE_COLUMNS.index("source_locator")
    by_rel = defaultdict(list)
    for e in edges:
        by_rel[e["relationship"]].append(e)
    for rel in sorted(by_rel):
        if rel not in RELATIONSHIPS:
            raise ValueError(f"unknown relationship {rel}")
        rows = by_rel[rel]
        for i in range(0, len(rows), batch):
            lst = ",\n  ".join(cy_row(r, EDGE_COLUMNS) for r in rows[i:i + batch])
            yield (f"UNWIND [\n  {lst}\n] AS r\nMATCH (a:Entity {{id: r[0]}}), (b:Entity {{id: r[1]}})\n"
                   f"MERGE (a)-[x:{rel} {{source_document: r[{di}], source_locator: r[{li}]}}]->(b) SET {edge_set};")


def write_script(nodes, edges, path, batch=500):
    with open(path, "w", encoding="utf-8") as f:
        f.write(HEADER.format(nodes=len(nodes), edges=len(edges)))
        for st in statements(nodes, edges, batch):
            f.write("\n" + st + "\n")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("csv_dir")
    ap.add_argument("out")
    ap.add_argument("--batch", type=int, default=500)
    args = ap.parse_args(argv)
    nodes, edges = read_graph(args.csv_dir)
    write_script(nodes, edges, args.out, args.batch)
    print(f"wrote {args.out}: {len(nodes)} nodes, {len(edges)} relationships")


if __name__ == "__main__":
    main()
